name: Deploy to Surge

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Surge
      run: npm install 

    - name: Deploy to Surge
      env:
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}  
      run: 
        npx surge ./src polite-sbaete.surge.sh --token $SURGE_TOKEN
